GensrcSwing.gmk: Remove gensrc from javadoc source path
The gensrc_no_srczip/_the.generated_beaninfo build rule does not use
any sources in gensrc.  Remove $(JDK_OUTPUTDIR)/gensrc from the
javadoc -sourcepath argument, because its presence there can cause
build failures.

Other build targets (for example,
gensrc/java/nio/_the.exceptions.dir), generate source code under that
path.  When make is invoked with more than one job, sometimes one of
those other targets will be in the process of writing a source file
when the _the.generated_beaninfo build rule invokes javadoc.  The
result is build failures of the form:

Generating beaninfo
[...]\jdk8u-dev\jdk\src\share\classes\java\io\PrintStream.java:32: error: cannot access UnsupportedCharsetException
import java.nio.charset.UnsupportedCharsetException;
                       ^
  bad source file: [...]\jdk8u-dev\build\windows-x64\jdk\gensrc\java\nio\charset\UnsupportedCharsetException.java